
* Perpose of this branch
** The reason why merge three github repository
사용하다가 보면 좋은 설정이 많지만, 각각 사용해 보면 내 입맞에 맞지는 않는다.
그래서 일부 기능이 괜챦은 것들을 모아서 합쳐 보려고 한다.
*** Daviwil
이분은 Youtube로 emacs 설정에 대해서 설명을 잘 해 주신 분이다.
e-lisp에 대한 좋은 글은 없어서 시작하기 어려웠는데 이 분 덕에 다시 시작할 마음을 먹었다.
이 분이 youtube에 만들어 둔 내용은 scratch 부터 하나 하나 추가해 가면서 만들어 가는 것인데, 따라서 해 보다 보면 중간 중간 되지 않는 부분이 있고, evil을 사용한다.
VI를 사용하지 않는 입장에서 이것이 들어가 봐야 헛갈리기만 할 뿐이므로  evil 관련 설정은 없애고자 한다.
(EVIL을 사용하는 것은 space emacs 처럼 새끼 손까락을 쓰지 않고 명령의 시작을 space로 하고자 함 일거라는 생각이 든다... 그럼 EVIL mode에 익숙해 져야 하는가?...)
그리고 이 분이 org로 발표하는 것도 상당히 인상적이다.
**** https://github.com/daviwil/emacs-from-scratch
*** Purcel
이 분은 Program 개발에 대해서는 거의 완벽한 설정이지만 전체적으로 이해를 하지는 못하므로 customization을 하기 어렵다. 문서화가 별로 되어 있지 않은 것 같으므로 문서를 좀 더 찾던지 하나씩 해 보면서 추가해야 한다.
그리고 설정에 org mode를 사용하지 않았다.
**** https://github.com/purcell/emacs.d
*** rksm
이 분의 설정은 rust programming에 대해서는 잘 돌아간다. 위쪽 Purcel 의 설정의 일부를 보강할 수 있으리라 생각한다.
**** https://github.com/rksm/emacs-rust-config

* ORG to el 변경
- .org file내에서 여러가지 elisp file 을 만들어 낼 수 있어야 한다. 이를 위해서는 ":tangle directory/filename :mkdirp yes" 를 넣어서 생성할 file을 지정해야 한다.
- file 변경은 "org2el.sh"를 써서 변경할 수 있다. (아래 참조)


* Org file batch converting
#+begin_src bash :tangle ./org2el.sh :mkdirp yes
  #!/bin/sh
  # Tangle files with Org mode
  #
  emacs -Q --batch --eval "
      (progn
        (require 'ob-tangle)
        (dolist (file command-line-args-left)
          (with-current-buffer (find-file-noselect file)
            (org-babel-tangle))))
    " "$@"
#+end_src

* Org file batch converting
#+begin_src bash :tangle ./change_org_configs.sh :mkdirp yes
  #!/bin/sh
  for fname in jsyang.org ; do sh org2el.sh $fname; done
#+end_src

